ruby/rails/pjdoc/config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
  	resources :comments # Adicionando rotas para comments (FILHOS) (1..*)
  end


  root 'welcome#index'
  # get '/articles/:id' => 'articles#show'
  # get '/articles' => 'articles#index'
end

ruby/rails/pjdoc/app/models/article.rb
class Article < ActiveRecord::Base
	# Destruir os comentários caso artigo seja excluido.
	has_many :comments, :dependent => :destroy

	validates :title, presence: true, length: { minimum: 5} 
	validates :text, presence: true, length: { minimum: 20} 
end

ruby/rails/pjdoc/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :commenter, presence: true, length: { minimum: 5} 
  validates :body, presence: true, length: { minimum: 20} 
end

ruby/rails/pjdoc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/rails/pjdoc/app/controllers/articles_controller.rb
require 'base64'

class ArticlesController < ApplicationController

	# http_basic_authenticate_with :login => 'anderson', :pass => '121181', :except => [:index, :show]
	
	def index
		@articles = Article.all
	end
	 
	def show
	    @article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end


	def create
		# Apenas para mostrar na tela.
		# render plain: params[:article].inspect 

		# Gravando adicionando campos para tal.
		# @article = Article.new(params.require(:article).permit(:title, :text))
		
		# picture = Base64.encode64()
		# @article.picture = picture
		# @article.picture = Base64.encode64(@article.picture)

		@article = Article.new(article_params)

		file_upload = params[:article][:picture]
		@article.picture = Base64.urlsafe_encode64(file_upload)

		puts @article.picture

		if @article.save
			redirect_to @article
		else
			render 'new' # Renderiza o proprio formulário NEW.
		end
		
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		if @article.destroy
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	# Adicionar parametros para nao serem adicionados 
	# fora do contexto pretentido:
	private 
		def article_params
			params.require(:article).permit(:title, :text, :picture)
		end
end

ruby/rails/pjdoc/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# http_basic_authenticate_with :login => 'anderson', :pass => '121181', :except => [:index, :show]

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to @article
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = Comment.find(params[:id])
		@id = @comment.article_id
		if @comment.destroy
			redirect_to article_path(@article)
		else
			redirect_to articles_path
		end
	end

	private 
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

ruby/rails/pjdoc/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ruby/rails/pjdoc/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/rails/pjdoc/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby/rails/pjdoc/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/rails/pjdoc/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ruby/rails/pjdoc/app/views/articles/_comment.html.erb
<h3>Comments</h3>
<% @article.comments.each do |comment| %>
	  <p>
	    <strong>Commenter:</strong>
	    <%= comment.commenter %>
	  </p>
	 
	  <p>
	    <strong>Comment:</strong>
	    <%= comment.body %>
	  </p>
		
		<%# Minha versão: %>
	   <%# link_to 'Delete', article_comment_path(@article.id, comment.id), :method => :delete, :data => { :confirm => 'Are you sure?' } %>

	   <%# Versão utilizada pelo site %>
	   <%= link_to 'Delete',  [comment.article, comment], :method => :delete, :data => { :confirm => 'Are you sure?' } %>
<% end %>

<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

ruby/rails/pjdoc/app/views/articles/_form.html.erb
<div class="col-md-offset-2 col-md-8 col-md-offset-2">
  <%= form_for @article, :multipart => true do |f| %> <% if @article.errors.any?  %>

  <div class="form-group">
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article
        from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :title %> 
    <%= f.text_field :title, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :text %> 
    <%= f.text_area :text, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :picture %> 
    <%= f.text_field :picture, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= link_to 'Back', articles_path %> <%= f.submit %>
  </div>

  <% end %>
</div>

ruby/rails/pjdoc/app/views/articles/edit.html.erb
<h1><b>Edit</b></h1>
<%= render 'form' %>
<%= link_to 'Back', article_path %>
<%= link_to 'Delete', article_path(@article), :method => :delete, :data => { confirm: 'Are you sure?' }%>

ruby/rails/pjdoc/app/views/articles/index.html.erb
<div class="col-md-12">
	<div class="form-group">
		
	</div>
	<h1>Index</h1>
<% @articles.each do |article| %>
	<h3><%= article.title %></h3>
	<p><%= article.text %></p>
	<p><%= link_to "Selecionar", controller: "articles", action: "show", id: article.id %></p>
	<hr>
<% end %>


<%= link_to 'New Article', new_article_url %>

</div>

ruby/rails/pjdoc/app/views/articles/new.html.erb
<h1><b>Create</b></h1>
<%= render 'form' %>

ruby/rails/pjdoc/app/views/articles/show.html.erb
<h1>Show</h1>
<p>
	<strong>
		Title
	</strong>
	<%= @article.title %>
</p>
<p>
	<strong>
		Text
	</strong>
	<%= @article.text %>
</p>

<p>
	<%= link_to 'Edit', edit_article_path(@article) %>
</p>

<%= render 'comment' %>

ruby/rails/pjdoc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pjdoc</title>
		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
			integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
			crossorigin="anonymous"/>

		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
			integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
			crossorigin="anonymous"/>

		<script
			src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
			integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
			crossorigin="anonymous"></script>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %> 
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

ruby/rails/pjdoc/app/views/welcome/index.html.erb
<h1><b>Lorem Ipsum</b></h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= link_to 'Articles', controller: 'articles' %>